version: "3" 
  
services: 
  gotify: 
    image: gotify/server 
    container_name: gotify 
    restart: unless-stopped 
    volumes: 
      - "/patch/to/data:/app/data" 
    environment: 
      - GOTIFY_DEFAULTUSER_PASS=xxxxxxxxxxxxxxxxx
      - TRAEFIK_GOTIFY=gotify.example.com 
    networks: 
      - proxy 
    labels: 
      - "traefik.enable=true" 
      - "traefik.http.routers.gotify.rule=Host(`${TRAEFIK_GOTIFY}`)" 
      - "traefik.http.routers.gotify.entrypoints=https" 
      - "traefik.http.routers.gotify.tls=true" 
      - "traefik.http.routers.gotify.tls.certresolver=mydnschallenge" 
  
      # Watchtower Update 
      - "com.centurylinklabs.watchtower.enable=true" 
  
networks: 
  proxy: 
    external: true 