version: '3.7' 
  
  
services: 
  influxdb: 
    image: influxdb 
    container_name: influxdb 
    volumes: 
      - /patch/to/data/influxdb/data:/var/lib/influxdb
      - /patch/to/data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf 
    networks: 
      - red 
      - internal 
    labels: 
      - "traefik.backend=influxdb" 
      - "traefik.enable=true" 
      - "traefik.frontend.rule=Host:influxdb.example.com" 
      - "traefik.port=8086" 
      - "traefik.docker.network=red" 
      - "traefik.enable=true" 
      - "traefik.http.middlewares.securedi.chain.middlewares=influxdb,lista-blanca" 
      - "traefik.http.routers.influxdb.middlewares=securedi" 
      - "traefik.http.middlewares.lista-blanca.ipwhitelist.sourcerange=XX.XX.XX.XX, XX.XX.XX.XX" 
  
  grafana: 
    image: grafana/grafana 
    container_name: grafana 
    environment: 
      - GF_SERVER_ROOT_URL=https://grafana.example.com 
      - GF_EXTERNAL_IMAGE_STORAGE=local 
      - GF_INSTALL_PLUGINS=grafana-piechart-panel 
    networks: 
      - red 
      - internal 
    volumes: 
      - /patch/to/data/grafana/data:/var/lib/grafana 
    labels: 
      - "traefik.backend=grafana" 
      - "traefik.enable=true" 
      - "traefik.frontend.rule=Host:grafana.example.com" 
      - "traefik.port=3000" 
      - "traefik.docker.network=red" 
  
  telegraf: 
    image: telegraf:latest 
    container_name: telegraf 
    volumes: 
      - /patch/to/data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  prometheus: 
    image: prom/prometheus:latest 
    container_name: prometheus 
    volumes: 
      - /patch/to/data/prometheus/data:/prometheus 
      - /patch/to/data/prometheus/etc:/etc/prometheus 
    networks: 
      - internal 