--- 
version: "3.3" 

services:
  jenkins:
    # https://hub.docker.com/r/jenkins/jenkins/
    image: jenkinsci/blueocean:latest
    restart: always
    networks:
      - red
    expose:
      - "80"
      # remove the '#' below only if you want access from remote JNLP agents
      #- "50000"
    volumes:
      # Ensure Jenkins content persist between restarts.
      - vol-jenkins-content:/var/jenkins_home 
      # remove the '#' if you want to run blueocean docker agents (advanced only)
      #- /var/run/docker.sock:/var/run/docker.sock
    environment:
      - http_port=80
    labels:
      - "traefik.docker.network=frontend"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${JENKINS_DOMAINS}"
      - "traefik.port=80"
      - "traefik.protocol=http"

networks: 
  red: 
    external: true 