version: '3' 
  
services: 
transmission: 
    image: 'linuxserver/transmission:latest' 
    container_name: transmission 
    restart: unless-stopped 
    volumes: 
      - ./data/config:/config 
      - ./data/downloads:/downloads 
      - ./data/watch:/watch 
    environment: 
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
      - USER=${WEB_USER} 
      - PASS=${WEB_PASS} 
    ports: 
      - 51413:51413 
      - 51413:51413/udp 
    networks: 
      - proxy 
    labels: 
      - "traefik.enable=true" 
      - "traefik.http.routers.transmission.rule=Host(`${TRAEFIK_TRANSMISSION}`)" 
      - "traefik.http.routers.transmission.entrypoints=https" 
      - "traefik.http.routers.transmission.tls=true" 
      - "traefik.http.routers.transmission.tls.certresolver=mydnschallenge" 
      - "traefik.http.services.transmission.loadbalancer.server.port=9091" 
      # Watchtower Update 
      - "com.centurylinklabs.watchtower.enable=true" 
  
networks: 
  proxy: 
    external: true 
 
 
.env 
TRAEFIK_TRANSMISSION=transmission.example.com 
TZ=Europe/Paris 
WEB_USER=xxxxxxxxxxxxxxx 
WEB_PASS=xxxxxxxxxxxxxxx 
  
# user PUID and group PGID - can be found by running id your-user 
PUID=1000 
PGID=1000 